# Generated by Django 4.0.5 on 2022-06-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_project_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
